/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Deal, NotificationItem, Sighting, SavedLocation, CommuteRoute } from './types';

export const INITIAL_DEALS: Deal[] = [
  {
    id: '1',
    shop: "Café Zest",
    emoji: "☕",
    cat: "food",
    tag: "tag-food",
    title: "50% off All Beverages",
    disc: 50,
    dist: 0.2,
    expiry: 7020,
    flash: true,
    rating: 4.8,
    worthit: 94,
    sightingsCount: 12,
    desc: "All hot and cold drinks at half price. Valid for dine-in only. Includes specialty coffees, teas, and cold brew.",
    lat: 36,
    lng: 18,
    saved: false,
    orig: 650,
    price: 325
  },
  {
    id: '2',
    shop: "TechZone",
    emoji: "📱",
    cat: "electronics",
    tag: "tag-electronics",
    title: "iPhone Case Bundle - 3 for 1",
    disc: 66,
    dist: 0.45,
    expiry: 28800,
    flash: false,
    rating: 4.5,
    worthit: 88,
    sightingsCount: 5,
    desc: "Pick any 3 premium phone cases for the price of one. Covers all major brands.",
    lat: 22,
    lng: 45,
    saved: true,
    orig: 3600,
    price: 1200
  },
  {
    id: '3',
    shop: "Zara Outlet",
    emoji: "👗",
    cat: "fashion",
    tag: "tag-fashion",
    title: "End of Season - 40% Off",
    disc: 40,
    dist: 0.7,
    expiry: 86400,
    flash: false,
    rating: 4.2,
    worthit: 81,
    sightingsCount: 23,
    desc: "Selected styles from the spring collection at 40% off. In-store only.",
    lat: 55,
    lng: 68,
    saved: false,
    orig: 8500,
    price: 5100
  },
  {
    id: '4',
    shop: "GlowUp Studio",
    emoji: "💇‍♀️",
    cat: "beauty",
    tag: "tag-beauty",
    title: "Facial + Massage Combo",
    disc: 35,
    dist: 0.3,
    expiry: 18000,
    flash: true,
    rating: 4.9,
    worthit: 97,
    sightingsCount: 8,
    desc: "60-minute facial paired with a 30-minute shoulder & neck massage by certified therapists.",
    lat: 40,
    lng: 72,
    saved: true,
    orig: 4500,
    price: 2925
  },
  {
    id: '5',
    shop: "FitZone Gym",
    emoji: "🏋️‍♂️",
    cat: "sports",
    tag: "tag-sports",
    title: "Monthly Membership Deal",
    disc: 30,
    dist: 0.9,
    expiry: 172800,
    flash: false,
    rating: 4.3,
    worthit: 79,
    sightingsCount: 3,
    desc: "First month at 30% off. Full facility access, group classes, and free trainer session.",
    lat: 18,
    lng: 56,
    saved: false,
    orig: 6000,
    price: 4200
  },
  {
    id: '6',
    shop: "HomeSense",
    emoji: "🛋️",
    cat: "home",
    tag: "tag-home",
    title: "Buy 2 Get 1 Free - Cushions",
    disc: 33,
    dist: 0.5,
    expiry: 43200,
    flash: false,
    rating: 4.0,
    worthit: 72,
    sightingsCount: 6,
    desc: "Mix and match any cushion covers and throws from the entire range.",
    lat: 64,
    lng: 34,
    saved: false,
    orig: 2400,
    price: 1600
  },
  {
    id: '7',
    shop: "Burger Bros",
    emoji: "🍔",
    cat: "food",
    tag: "tag-food",
    title: "Double Burger Wednesday",
    disc: 50,
    dist: 0.15,
    expiry: 10800,
    flash: true,
    rating: 4.7,
    worthit: 92,
    sightingsCount: 31,
    desc: "Every Wednesday: buy one double smash burger, get one free. Dine-in or takeaway.",
    lat: 48,
    lng: 27,
    saved: true,
    orig: 1200,
    price: 600
  },
  {
    id: '8',
    shop: "Luxe Watches",
    emoji: "⌚",
    cat: "electronics",
    tag: "tag-electronics",
    title: "Clearance - Up to 60% Off",
    disc: 60,
    dist: 1.2,
    expiry: 259200,
    flash: false,
    rating: 4.1,
    worthit: 76,
    sightingsCount: 4,
    desc: "Premium watch brands clearing last season inventory. Limited pieces available.",
    lat: 75,
    lng: 60,
    saved: false,
    orig: 45000,
    price: 18000
  },
  {
    id: '9',
    shop: "Sushi Maru",
    emoji: "🍣",
    cat: "food",
    tag: "tag-food",
    title: "Lunch Set - 45% Off",
    disc: 45,
    dist: 0.6,
    expiry: 5400,
    flash: true,
    rating: 4.6,
    worthit: 89,
    sightingsCount: 19,
    desc: "Premium 8-piece sushi set with miso soup and salad. Lunch hours only, 12-3 PM.",
    lat: 32,
    lng: 50,
    saved: false,
    orig: 2200,
    price: 1210
  },
  {
    id: '10',
    shop: "Sole Street",
    emoji: "👟",
    cat: "fashion",
    tag: "tag-fashion",
    title: "Nike & Adidas 25% Off",
    disc: 25,
    dist: 0.8,
    expiry: 129600,
    flash: false,
    rating: 4.4,
    worthit: 83,
    sightingsCount: 14,
    desc: "All branded sports shoes on sale this weekend. Select styles, while stocks last.",
    lat: 60,
    lng: 75,
    saved: false,
    orig: 12000,
    price: 9000
  },
  {
    id: '11',
    shop: "The Brew Lab",
    emoji: "🍹",
    cat: "food",
    tag: "tag-food",
    title: "Happy Hour: 2 for 1 Drinks",
    disc: 50,
    dist: 0.25,
    expiry: 3600,
    flash: true,
    rating: 4.5,
    worthit: 91,
    sightingsCount: 22,
    desc: "5-7 PM every day. All draft options and mocktails. Bar seating only.",
    lat: 43,
    lng: 14,
    saved: false,
    orig: 900,
    price: 450
  },
  {
    id: '12',
    shop: "EcoHome",
    emoji: "🌿",
    cat: "home",
    tag: "tag-home",
    title: "Indoor Plants Bundle",
    disc: 20,
    dist: 1.0,
    expiry: 345600,
    flash: false,
    rating: 3.9,
    worthit: 68,
    sightingsCount: 2,
    desc: "6-plant starter set with soil and ceramic pots. Perfect for beginners.",
    lat: 14,
    lng: 80,
    saved: false,
    orig: 3500,
    price: 2800
  }
];

export const INITIAL_NOTIFS: NotificationItem[] = [
  {
    id: '1',
    type: 'deals',
    icon: '🔥',
    bg: 'rgba(255,77,109,0.15)',
    title: 'Flash Deal Alert',
    desc: 'Café Zest just dropped 50% off all beverages - 200m from you!',
    time: '2 min ago',
    read: false
  },
  {
    id: '2',
    type: 'expiry',
    icon: '⏳',
    bg: 'rgba(245,158,11,0.15)',
    title: 'Saved Deal Expiring',
    desc: 'Your bookmarked "GlowUp Facial Combo" expires in 2 hours.',
    time: '30 min ago',
    read: false
  },
  {
    id: '3',
    type: 'sightings',
    icon: '👥',
    bg: 'rgba(46,204,113,0.15)',
    title: 'Sighting Confirmed',
    desc: '3 users confirmed Burger Bros deal is still active & in stock.',
    time: '1 hr ago',
    read: false
  },
  {
    id: '4',
    type: 'deals',
    icon: '🌿',
    bg: 'rgba(77,159,255,0.15)',
    title: 'New Deal Near Home',
    desc: 'EcoHome added 20% off indoor plants deal, 1km from you.',
    time: '2 hr ago',
    read: true
  },
  {
    id: '5',
    type: 'route',
    icon: '🚗',
    bg: 'rgba(168,85,247,0.15)',
    title: 'Route Alert',
    desc: 'Sushi Maru has a flash lunch deal along your morning commute.',
    time: '3 hr ago',
    read: true
  }
];

export const INITIAL_SIGHTINGS: Sighting[] = [
  { id: 's1', dealId: '1', user: '@raza_eats', text: 'Burger deal confirmed - queue is fast!', time: '3m', emoji: '🍔' },
  { id: 's2', dealId: '3', user: '@shopaholic_pk', text: 'Zara sale real, sizes running out', time: '8m', emoji: '🛍️' },
  { id: 's3', dealId: '2', user: '@techbro404', text: 'TechZone cases legit, just grabbed mine', time: '22m', emoji: '📱' }
];

export const INITIAL_LOCS: SavedLocation[] = [
  { id: 'l1', name: 'Home', icon: '🏠', address: 'Gulberg III, Lahore', active: true },
  { id: 'l2', name: 'Work', icon: '💼', address: 'Liberty Market, Lahore', active: true },
  { id: 'l3', name: 'Gym', icon: '🏋️‍♂️', address: 'Johar Town, Lahore', active: false }
];

export const INITIAL_ROUTES: CommuteRoute[] = [
  {
    id: 'r1',
    from: 'Home (Gulberg III)',
    to: 'Office (Liberty)',
    active: true,
    dealsCount: 4,
    alertRadius: 400,
    startTime: '07:30',
    endTime: '09:30',
    categories: ['food', 'electronics']
  },
  {
    id: 'r2',
    from: 'Home',
    to: 'DHA Phase 5',
    active: false,
    dealsCount: 7,
    alertRadius: 500,
    startTime: '17:30',
    endTime: '19:30',
    categories: ['food', 'fashion', 'home']
  }
];
